// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using entityBasicoDAL;

#nullable disable

namespace entityBasicoDAL.Migrations
{
    [DbContext(typeof(AccesoDC))]
    [Migration("20221027092313_Version3")]
    partial class Version3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Empleadonivel_acc", b =>
                {
                    b.Property<int>("empleadosId")
                        .HasColumnType("integer");

                    b.Property<int>("nivel_accesosId")
                        .HasColumnType("integer");

                    b.HasKey("empleadosId", "nivel_accesosId");

                    b.HasIndex("nivel_accesosId");

                    b.ToTable("Empleadonivel_acc");
                });

            modelBuilder.Entity("entityBasicoDAL.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("nombre_empleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("entityBasicoDAL.nivel_acc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("desc_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nivel_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("nivel_acceso");
                });

            modelBuilder.Entity("Empleadonivel_acc", b =>
                {
                    b.HasOne("entityBasicoDAL.Empleado", null)
                        .WithMany()
                        .HasForeignKey("empleadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entityBasicoDAL.nivel_acc", null)
                        .WithMany()
                        .HasForeignKey("nivel_accesosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
