// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using entityBasicoDAL;

#nullable disable

namespace entityBasicoDAL.Migrations
{
    [DbContext(typeof(AccesoDC))]
    [Migration("20221027075311_pruebaMigracion1")]
    partial class pruebaMigracion1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("entityBasicoDAL.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("nombre_empleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("entityBasicoDAL.nivel_acc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("desc_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nivel_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("nivel_acceso");
                });

            modelBuilder.Entity("entityBasicoDAL.nivel_acc", b =>
                {
                    b.HasOne("entityBasicoDAL.Empleado", null)
                        .WithMany("nivel_accesos")
                        .HasForeignKey("EmpleadoId");
                });

            modelBuilder.Entity("entityBasicoDAL.Empleado", b =>
                {
                    b.Navigation("nivel_accesos");
                });
#pragma warning restore 612, 618
        }
    }
}
